
  - name: EIGRP Configuration
    hosts: R1
    gather_facts: no
    connection: network_cli
    tasks:
      - name: EIGRP R1
        cisco.ios.ios_config:
          parents: "router eigrp 10"
          lines:
          - network 192.168.1.0
          - network 192.168.2.0 0.0.0.3
          - network 192.168.6.0 0.0.0.3
          - network 192.168.0.0 0.0.0.3