# tasks file for EIGRP routing
#
- name: Enter EIGRP Process
  ios_config:
    lines:
      - "router eigrp 10"
    

- name: EIGRP Network IPV4
  ios_config:
    lines: 
      - " network {{ item.network}} {{item.mask}}"
    parents: router eigrp 10
  when:
    - eigrp is defined
    - eigrp.neighbors is defined
    - eigrp.neighbors.ipv4 is defined
  loop: "{{ eigrp.neighbors.ipv4 }}"
  
- name: EIGRP Network IPV6
  ios_config:
    lines: 
      - " ipv6 eigrp {{ item.eigrp.as}} "
    parents: "interface {{item.ios_if}}"
  when:
    - eigrp is defined
    - interface.eigrp is defined
    - ipv6 is defined
  loop: "{{interfaces}}"

- name: EIGRP Redistribute to OSPF (if exists)
  ios_config:
    lines:
      - "redistribute ospf {{ item.process}} "
    parents: router eigrp 10
  when:
    - eigrp is defined
    - eigrp.ospf is defined
  loop: "{{ eigrp.ospf}}"



