router_id: 192.168.1.1
rtr_role: edge
bgp:
  local_as: 65101
  redist:
    ospf: true
    ospfv3: true
  neighbors:
    ipv4:
     - peer: 10.100.101.254
       remote_as: 65430
       ebgp: true
     - peer: 192.0.2.201
       remote_as: 65101
       ibgp: true
       update_source: Loopback0
       default_originate: true
    ipv6:
     - peer: "2001:db8:101::ffff"
       remote_as: 65001
       ebgp: true

     - peer: "2001:db8:901:beef::2"
       remote_as: 65101
       ibgp: true
       update_source: Loopback0
interfaces:
  - ios_if: "GigabitEthernet0/0"
    desc: "Management"
    enabled: true
    ipv4: "192.168.10.1/30"


  - ios_if: "GigabitEthernet0/1"
    desc: "To R2"
    enabled: true
    ipv4: "192.168.2.1/24"
    ipv6: "2001:db8:cafe:2::1/64"

    ospf:
      area: "0.0.0.0"
      passive: true
    ospfv3:
      area: "0.0.0.0"
      passive: true

  - ios_if: "loopback0"
    desc: "Loopback"
    enabled: true
    ipv4: "192.168.6.1/24"
    ipv6: "2001:db8:cafe:6::1/64"
    ospf:
      area: "0.0.0.0"
      passive: true
    ospfv3:
      area: "0.0.0.0"
      passive: true
  - ios_if: "loopback1"
    desc: "Loopback"
    enabled: true
    ipv4: "192.168.1.1/24"
    ipv6: "2001:db8:cafe:1::1/64"
    ospf:
      area: "0.0.0.0"
      passive: true
    ospfv3:
      area: "0.0.0.0"
      passive: true

  