router_id: 192.168.3.1
#rtr_role: internal
eigrp:
  ospf:
   - process: 1
  neighbors:
    ipv4:
     - network: 192.168.2.0
       mask: 0.0.0.3
    ipv6:
     - peer: "2001:db8:901:beef::1"
       remote_as: 65101

interfaces:
  - ios_if: "GigabitEthernet0/0"
    desc: "To R1"
    enabled: true
    ipv4: "192.168.2.2/30"
    ipv6: "2001:db8:cafe:2::2/64"


  - ios_if: "GigabitEthernet0/2"
    desc: "To R3"
    enabled: true
    ipv4: "192.168.4.1/30"
    ipv6: "2001:db8:cafe:4::1/64"
    ospf:
      area: "0.0.0.0"
    ospfv3:
      area: "0.0.0.0"
  
  
  - ios_if: "loopback0"
    desc: "Loopback"
    enabled: true
    ipv4: "192.168.3.1/24"
    ipv6: "2001:db8:cafe:3::1/64"
    ospf:
      area: "0.0.0.0"
      passive: true
    ospfv3:
      area: "0.0.0.0"
      passive: true