router_id: 192.168.99.1
rtr_role: internal
bgp:
  local_as: 65100
  neighbors:
    ipv4:
     - peer: 192.168.99.1
       remote_as: 65000
       ebgp: true
       update_source: Loopback0
    ipv6:
     - peer: "2001:db8:99:1::1/64"
       remote_as: 65000
       ebgp: true
       update_source: Loopback0

#Interfaces for ISP router (R4)

interfaces:
  - ios_if: "GigabitEthernet0/0"
    desc: "To R3"
    enabled: true
    ipv4: "192.168.77.1/24"
    ipv6: "2001:db8:cafe:77::1/64"
    ospf:
      area: "0.0.0.0"
    ospfv3:
      area: "0.0.0.0"
  - ios_if: "loopback0"
    desc: "Loopback"
    enabled: true
    ipv4: "192.168.99.1/24"
    ipv6: "2001:db8:cafe:99::1/64"
    ospf:
      area: "0.0.0.0"
      passive: true
    ospfv3:
      area: "0.0.0.0"
      passive: true